//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileComm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9ABA01_voicetextEntities : DbContext
    {
        public DB_9ABA01_voicetextEntities()
            : base("name=DB_9ABA01_voicetextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TextOut> TextOuts { get; set; }
        public DbSet<VoiceOut> VoiceOuts { get; set; }
    }
}
